"""Extract SVG hit regions for the standalone layout prototype."""
from pathlib import Path
import json
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
SOURCES = {
    'xbox': 'xbox-one.svg', 'switch': 'switch.svg',
    'joycon': 'switch_joycon_processed.svg',
    'deck': 'steam-deck_processed.svg', 'keyboard': 'keyboard.svg',
    'mouse': 'mouse.svg',
}
ET.register_namespace('', 'http://www.w3.org/2000/svg')
SHAPES = {'path', 'rect', 'circle', 'ellipse', 'polygon', 'polyline'}
ATTRIBUTES = {'d', 'x', 'y', 'width', 'height', 'rx', 'ry', 'cx', 'cy', 'r',
              'points', 'transform', 'viewBox', 'data-button-id'}

def extract(node, active=False):
    active = active or 'data-button-id' in node.attrib
    tag = node.tag.split('}')[-1]
    if tag in {'defs', 'style', 'text', 'title', 'desc'}:
        return None
    children = [child for source in node if (child := extract(source, active)) is not None]
    if not children and not (active and tag in SHAPES):
        return None
    result = ET.Element(node.tag, {k: v for k, v in node.attrib.items() if k in ATTRIBUTES})
    result.extend(children)
    return result

data = {}
for device, filename in SOURCES.items():
    original = ET.parse(ROOT / 'controllers' / filename).getroot()
    overlay = extract(original)
    data[device] = ET.tostring(overlay, encoding='unicode')
target = Path(__file__).with_name('control-regions.js')
target.write_text('// Generated by extract-controls.py from local SVG hit regions.\n'
                  + 'const controlRegions = ' + json.dumps(data, ensure_ascii=True, indent=2)
                  + ';\n', encoding='utf-8', newline='\n')
