import { getControllerConfig } from '../constants/controllers'

/**
 * Render label for export (text only, no icon dependencies)
 */
const renderExportLabel = (label) => {
  if (!label) return null
  
  // Check if it's an icon class - if so, extract meaningful text or use as-is
  const isIcon = /^(bi bi-|fa[sbrldt]? fa-|fa )/.test(label)
  
  if (isIcon) {
    // Extract text from icon class names for better readability
    const iconMap = {
      'bi bi-dpad': '⊞',
      'bi bi-caret-up-fill': '▲',
      'bi bi-caret-down-fill': '▼',
      'bi bi-caret-left-fill': '◀',
      'bi bi-caret-right-fill': '▶',
      'fas fa-bars': '☰',
      'far fa-clone fa-rotate-90': '⧉',
      'bi bi-gear-fill': '⚙',
      'bi bi-three-dots': '⋯',
      'fas fa-plus': '+',
      'fas fa-minus': '−',
      'fas fa-house': '⌂',
      'bi bi-record-circle': '●'
    }
    
    return iconMap[label] || label.replace(/^(bi bi-|fa[sbrldt]? fa-|fa )/, '')
  }
  
  // Return plain text or Unicode character
  return label
}

/**
 * ControllerExportView - A component optimized for exporting controller mappings as an image
 * Displays the controller image with all mappings organized in lists
 */
function ControllerExportView({ controller, context, mappings }) {
  // Get controller-specific configuration from centralized source
  const config = getControllerConfig(controller)

  // Extract gesture information from mapping
  const getGestures = (mapping) => {
    if (!mapping) return []

    const gestures = []
    
    // Handle new multi-gesture format
    if (typeof mapping === 'object' && !mapping.action) {
      ['direction', 'press', 'hold'].forEach(gestureType => {
        if (mapping[gestureType] && mapping[gestureType].action) {
          gestures.push({
            type: gestureType,
            action: mapping[gestureType].action,
            description: mapping[gestureType].description || ''
          })
        }
      })
    }
    // Handle single-gesture format
    else if (typeof mapping === 'object' && mapping.action) {
      gestures.push({
        type: mapping.gesture || 'action',
        action: mapping.action,
        description: mapping.description || ''
      })
    }
    // Handle legacy string format
    else if (typeof mapping === 'string') {
      gestures.push({
        type: 'action',
        action: mapping,
        description: ''
      })
    }

    return gestures
  }

  // Build list of all mappings in order
  const mappingsList = config.buttons
    .filter(button => mappings[button.id])
    .map(button => ({
      button,
      gestures: getGestures(mappings[button.id])
    }))

  return (
    <div className="controller-export-view">
      <div className="export-header">
        <h1>{config.name} - {context}</h1>
      </div>
      
      <div className="export-content">
        <div className="export-controller-image">
          <img src={config.image} alt={config.name} />
        </div>
        
        <div className="export-mappings-list">
          <h2>Button Mappings</h2>
          {mappingsList.length === 0 ? (
            <div className="no-mappings">
              <p>No mappings configured for this context</p>
            </div>
          ) : (
            <div className="export-mappings-table">
              {mappingsList.map(({ button, gestures }) => (
                <div key={button.id} className="export-mapping-row">
                  <div className="export-button-name">
                    {renderExportLabel(button.label)}
                  </div>
                  <div className="export-actions">
                    {gestures.map((gesture, idx) => (
                      <div key={idx} className="export-gesture">
                        <span className="export-gesture-type">{gesture.type}:</span>
                        <span className="export-action-name">{gesture.action}</span>
                        {gesture.description && (
                          <span className="export-description">({gesture.description})</span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
      
      <div className="export-footer">
        <p>Generated by Controller Scheme Designer</p>
      </div>
    </div>
  )
}

export default ControllerExportView
