import { useMemo, useRef } from 'react'
import { getControllerConfig } from '../controllers/registry'
import ControllerArtwork from '../controllers/ControllerArtwork'
import { getOrganizedButtons } from '../mappings/model/organization'
import ExportMappingList from './ExportMappingList'
import useExportConnections from './useExportConnections'

const EMPTY = {}

export default function ControllerExportView({
  controller, context, mappings, buttonSideOverrides = EMPTY, customOrder = EMPTY, showLines = true,
}) {
  const containerRef = useRef(null)
  const imageRef = useRef(null)
  const config = getControllerConfig(controller)
  const organized = useMemo(() => getOrganizedButtons(config.buttons, mappings, buttonSideOverrides, customOrder),
    [config, mappings, buttonSideOverrides, customOrder])
  const orderedButtons = useMemo(() => [...organized.sortedLeftButtons, ...organized.sortedRightButtons], [organized])
  const connections = useExportConnections(containerRef, imageRef, orderedButtons, mappings, config, showLines)
  return (
    <div className="controller-export-view" ref={containerRef}>
      <div className="export-header"><h1>{config.name} - {context}</h1></div>
      <div className="export-content">
        <ExportMappingList side="left" buttons={organized.sortedLeftButtons} mappings={mappings} />
        <div className="export-controller-image">
          <ControllerArtwork controller={controller} ref={imageRef} mappings={mappings} />
        </div>
        <ExportMappingList side="right" buttons={organized.sortedRightButtons} mappings={mappings} />
      </div>
      {/* SVG overlay for connection lines */}
      {showLines && connections.length > 0 && (
        <svg className="export-connection-lines" style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          pointerEvents: 'none',
          zIndex: 1
        }}>
          {connections.map((conn) => (
            <g key={conn.buttonId}>
              {/* Line path with color variation to distinguish overlaps */}
              <path
                d={conn.path}
                stroke={conn.color}
                strokeWidth="1.5"
                fill="none"
                opacity="0.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              {/* Start circle (on button) */}
              <circle
                cx={conn.startX}
                cy={conn.startY}
                r="3"
                fill={conn.color}
                opacity="0.7"
              />
              {/* End circle (at row) */}
              <circle
                cx={conn.endX}
                cy={conn.endY}
                r="3"
                fill={conn.color}
                opacity="0.7"
              />
            </g>
          ))}
        </svg>
      )}
      
      <div className="export-footer">
        <p>Generated by Controller Scheme Designer</p>
      </div>
    </div>
  )
}
